// frontend/src/cards.ts
// Base de datos de cartas para el frontend
export const CARDS_INFO = [
  { name: "Yon", imagePath: "cards/Carta_1.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Igna", imagePath: "cards/Carta_2.jpg", baseAtk: 500, baseDef: 500 },
  { name: "Ado", imagePath: "cards/Carta_3.jpg", baseAtk: 500, baseDef: 500 },
  { name: "Osado", imagePath: "cards/Carta_4.jpg", baseAtk: 1000, baseDef: 0 },
  { name: "Bortex", imagePath: "cards/Carta_5.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Mizuki", imagePath: "cards/Carta_6.jpg", baseAtk: 0, baseDef: 1000 },
  { name: "Lin", imagePath: "cards/Carta_7.jpg", baseAtk: 250, baseDef: 750 },
  { name: "Flin", imagePath: "cards/Carta_8.jpg", baseAtk: 500, baseDef: 500 },
  { name: "Lia", imagePath: "cards/Carta_9.jpg", baseAtk: 1000, baseDef: 0 },
  { name: "Endy", imagePath: "cards/Carta_10.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Yukki Udagawa", imagePath: "cards/Carta_11.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Cockito", imagePath: "cards/Carta_12.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Holy Knight", imagePath: "cards/Carta_13.jpg", baseAtk: 750, baseDef: 250 },
  { name: "Primuss", imagePath: "cards/Carta_14.jpg", baseAtk: 250, baseDef: 750 },
  { name: "Foxy Sutaru", imagePath: "cards/Carta_15.jpg", baseAtk: 550, baseDef: 450 },
  { name: "ZeroV0lt", imagePath: "cards/Carta_16.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Compadrito", imagePath: "cards/Carta_17.jpg", baseAtk: 0, baseDef: 1000 },
  { name: "Migue", imagePath: "cards/Carta_18.jpg", baseAtk: 1000, baseDef: 0 },
  { name: "Natari", imagePath: "cards/Carta_19.jpg", baseAtk: 500, baseDef: 500 },
  { name: "Kimura", imagePath: "cards/Carta_20.jpg", baseAtk: 300, baseDef: 700 },
  { name: "Trester", imagePath: "cards/Carta_21.jpg", baseAtk: 100, baseDef: 600 },
  { name: "Tomoe", imagePath: "cards/Carta_23.jpg", baseAtk: 500, baseDef: 500 },
  { name: "Yumiko", imagePath: "cards/Carta_24.jpg", baseAtk: 1000, baseDef: 0 },
  { name: "Rekky", imagePath: "cards/Carta_25.jpg", baseAtk: 600, baseDef: 400 },
  { name: "Niños", imagePath: "cards/Carta_26.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Espada", imagePath: "cards/Carta_27.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Puños", imagePath: "cards/Carta_28.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Mascara", imagePath: "cards/Carta_29.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Paz", imagePath: "cards/Carta_30.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Propuesta", imagePath: "cards/Carta_31.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Caos", imagePath: "cards/Carta_32.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Parry", imagePath: "cards/Carta_33.jpg", baseAtk: 1000, baseDef: 0 },
  { name: "Worthcat", imagePath: "cards/Carta_34.jpg", baseAtk: 150, baseDef: 850 },
  { name: "Ataque Sorpresa", imagePath: "cards/Carta_35.jpg", baseAtk: 0, baseDef: 0 },
  { name: "MalaMujer", imagePath: "cards/Carta_36.jpg", baseAtk: 450, baseDef: 550 },
  { name: "Verdadera", imagePath: "cards/Carta_37.jpg", baseAtk: 300, baseDef: 300 },
  { name: "BajoPerfil", imagePath: "cards/Carta_38.jpg", baseAtk: 0, baseDef: 0 },
  { name: "DobleONada", imagePath: "cards/Carta_39.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Neru", imagePath: "cards/Carta_40.jpg", baseAtk: 650, baseDef: 350 },
  { name: "Interesante", imagePath: "cards/Carta_41.jpg", baseAtk: 550, baseDef: 450 },
  { name: "TwistedZid", imagePath: "cards/Carta_42.jpg", baseAtk: 400, baseDef: 600 },
  { name: "Secreto", imagePath: "cards/Carta_43.jpg", baseAtk: 500, baseDef: 500 },
  { name: "Comienzo", imagePath: "cards/Carta_44.jpg", baseAtk: 500, baseDef: 500 },
  { name: "Maxwell", imagePath: "cards/Carta_45.jpg", baseAtk: 600, baseDef: 400 },
  { name: "Alto Mando", imagePath: "cards/Carta_46.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Lluvia de Ideas", imagePath: "cards/Carta_47.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Día de Playa (Chicos)", imagePath: "cards/Carta_48.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Día de Playa (Chicas)", imagePath: "cards/Carta_49.jpg", baseAtk: 0, baseDef: 0 },
  { name: "Y Eso Sería Todo por Hoy", imagePath: "cards/Carta_50.jpg", baseAtk: 0, baseDef: 0 },
];
